### ISSUE TITLE
[FEATURE]: Return pd.DataFrame if X is DataFrame after split

### ISSUE THREAD

**Issue by pikakolendo02** [JacksonBurns/astartes#125]
**Is your feature request related to a problem? Please describe.**

If X is a DataFrame with meaningful index, X_train and X_test are ndarrays without original index.

**Use-cases/examples of this new feature**

Return X_train, X_test as pd.DataFrame, y_train, y_test as pd.Series (or DataFrame, based on what y is).

**Desired solution/workflow**

Just like this package: https://github.com/yu9824/kennard_stone

**Discussion**

**Additional context**
Thank you!

**Comment by pikakolendo02** [comment]
I also noticed the builtin K-S algorithm is quite slow compared to yu9824's code. Could it be the same as yu9824's?

**Comment by JacksonBurns** [comment]
> Return X_train, X_test as pd.DataFrame, y_train, y_test as pd.Series (or DataFrame, based on what y is).

We will definitely implement this - particularly for pandas dataframes which we know are enormously popular.

> I also noticed the builtin K-S algorithm is quite slow compared to yu9824's code. Could it be the same as yu9824's?

We actually used to exclusively use that implementation and ultimately stepped away from it. yu9824's code will automatically normalize the input space and drop features with zero variance. While this does improve the speed, we don't want to modify the user's inputs without them knowing - especially to us, where the features are interpretatable and need to remain as they were input.

The KS algorithm in `astartes` was written by us and is much faster on datasets with fewer than 500 samples, which was the limit of our testing (so thanks for bringing this up!). I have now done extensive performance tuning on the KS sampler and managed to beat that implementation by a lot - I will open a PR now.

**Comment by JacksonBurns** [comment]
> > I also noticed the builtin K-S algorithm is quite slow compared to yu9824's code. Could it be the same as yu9824's?
> 
> We actually used to exclusively use that implementation and ultimately stepped away from it. yu9824's code will automatically normalize the input space and drop features with zero variance. While this does improve the speed, we don't want to modify the user's inputs without them knowing - especially to us, where the features are interpretatable and need to remain as they were input.
> 
> The KS algorithm in `astartes` was written by us and is much faster on datasets with fewer than 500 samples, which was the limit of our testing (so thanks for bringing this up!). I have now done extensive performance tuning on the KS sampler and managed to beat that implementation by a lot - I will open a PR now.

1.0.2 is now out (see #126) is out and now implement this :tada:!

**Comment by JacksonBurns** [comment]
Thanks @pikakolendo02!

We have now merged #127 which also adds support for some Pandas types.
