### ISSUE TITLE
[FEATURE]: split by property value

### ISSUE THREAD

**Issue by kevingreenman** [JacksonBurns/astartes#168]
Similar idea to #165, but a sampler could be designed to take a set of molecules (each with a corresponding scalar regression property value) as input, sort the molecules by property value, and put the molecules with highest property values into the test set. There could also be an argument for the user to toggle whether the highest or lowest property values go into the test set.

**Comment by JacksonBurns** [comment]
Great idea - thanks to @kspieks for the quick implementation, I will take a look at that PR and we can try and get it merged quickly!
