### ISSUE TITLE
Potentially add factory

### ISSUE THREAD

**Issue by kspieks** [JacksonBurns/astartes#52]
One idea to avoid these many if statements [link](https://github.com/JacksonBurns/astartes/pull/48/commits/cc8d80b8aec44a3ea6b3a568bb6210785234702c#diff-0a557dc56cfc769c5aced482f0a64b9ae92eec3369e75bbae81c9e0bebd73b13L47-L54) is to add a factory. An example is the ESS adapter and factory in RMG-Py's Arkane so at the bottom of each adapter we just add a line to register the adapter [link](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/arkane/ess/gaussian.py#L552) then we could just do something like `_registered_adapters[sampler_name]` rather than a long chain of if, elif, elif, elif, elif, elif etc

**Comment by JacksonBurns** [comment]
This is a nice design pattern -- I will do it and open a PR.
