### ISSUE TITLE
[FEATURE]: SPlit method for partitioning data

### ISSUE THREAD

**Issue by himaghna** [JacksonBurns/astartes#70]
https://arxiv.org/pdf/2012.10945.pdf

**Comment by JacksonBurns** [comment]
Bumping this to v1.x of astartes

**Comment by JacksonBurns** [comment]
Source code for this algorithm is available in R [here](https://cran.r-project.org/package=SPlit).

**Comment by JacksonBurns** [comment]
Closing this as not planned for time being - we have plenty of samplers as it is, and this one does not have any promising features not already mostly provided by existing samplers, especially Kennard-Stone in this case.
