### ISSUE TITLE
[FEATURE]: Put in rdkit objects directly

### ISSUE THREAD

**Issue by ericchen384** [JacksonBurns/astartes#84]
**Is your feature request related to a problem? Please describe.**

I have a bunch of adsorbed species, and can make then directly into rdkit objects fairly easily. However, to make them into astartes/AIMSIM inputs, I convert it back into a smiles string, and then input it in.

**Use-cases/examples of this new feature**

Periodic DFT adsorbed structure can be approximated with a chunk of the surface the adsorbate is put on + the adsorbate; this gives very complicated SMILES strings, plus rdkit has to sanitize them. 
I can get my geometries into rdkit format just the way I need to, but converting it to a SMILES string is a roundabout way to to analytics on it.

**Desired solution/workflow**

Unfortunately I have no idea what pseudocode would do this, but being  able to put in a list of rdkit objects as input would be massively helpful.

**Discussion**

**Additional context**

Thank you!

**Comment by JacksonBurns** [comment]
Hi @ericchen384 thanks for this feature suggestion!

Agreed that the current implementation can lead to a very odd workflow (User Input -> RDKit object -> SMILES -> RDKit object) and it would be much better to directly support the passing of RDKit objects.

In the background, `astartes` turns the SMILES strings into RDKit objects, and from there calculates the molecular fingerprint according to the user configuration (the morgan fingerprint by default). __Would it still make sense to use morgan fingerprints for adsorbed species?__ Is there a better option?

Would it be better to somehow compare the graphs instead?

**Comment by ericchen384** [comment]
Hi Jackson,

I don't think it's a bad start; it makes more sense for adsorbates on a cluster than it will for an extended surface. If I were to convert an extended surface into a graph, my first-thought naive solution uses a cyclic graph to represent the periodicity, which morphs the structure from an extended surface to a wacky warped cluster. This will also lose slab size-based coverage information.
That said, I think ECFP would be able to get all the substructures needed from a graph like this so long as the radius stays appropriately small and doesn't find loops that don't actually exist due to the lack of periodicity. This will also lose slab size-based coverage information.

On an implementation issue, there are many cases where I've had trouble getting a Morgan fingerprint from rdkit because we cannot sanitize the molecule to rdkit standards; ex. Methoxy on a(n?) 111 facet hollow site, where the O is bound to four atoms.

**Comment by JacksonBurns** [comment]
I have implemented the ability to pass in RDKit objects directly now! I think this will be a great addition. It will be up to users to make sure they configure the fingerprint to avoid the issues you mentioned, but I trust our expert users to understand their own use cases.

To deal with the possibility of structures not generating fingerprints, I also added some extra logic to catch those issues and give the user more helpful feedback. (Unfortunately can't actually [capture RDKit logging output](https://sourceforge.net/p/rdkit/mailman/message/30036309/)). I will let you know when we move to release candidates so you can try this out! Thanks again for the suggestion!
