### ISSUE TITLE
[BUG]: Error instantiating train_test_split_molecules()

### ISSUE THREAD

**Issue by ericchen384** [JacksonBurns/astartes#85]
**Describe the bug**

Using the example train_test_split_molecules() settings in the readme, but commenting out the y=y (just want to get out group splits), I get the following error:
TypeError: train_test_split_molecules() got an unexpected keyword argument 'splitter'

**Example(s)**

smiles = list(open('smiles.txt')

    train_test_split_molecules(
    smiles=smiles,
    # y=y,
    test_size=0.2,
    train_size=0.8,
    fingerprint="daylight_fingerprint",
    fprints_hopts={
        "minPath": 2,
        "maxPath": 5,
        "fpSize": 200,
        "bitsPerHash": 4,
        "useHs": 1,
        "tgtDensity": 0.4,
        "minSize": 64,
    },
    splitter="random",
    hopts={
        "random_state": 42,
        "shuffle": True,
    },
    )

**Expected behavior**

Expected train_test_split instance

**Screenshots**

**Environment**

- 3.11
- package versions: aimsim-2.0.2, astartes 1.0.0b2
- Windows

**Checklist**

- [ ] the unit tests are working: `pytest -v` reports no errors: Error collecting test session

**Additional context**

**Comment by JacksonBurns** [comment]
Hi @ericchen384 thanks for caching this! In this case the documentation was just out of date. The call should be `sampler = "name"` instead of `splitter` -- previous versions used a different keyword.

I have updated the README with this change.
